name: react CD

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/job-application-tracker-front
            echo REACT_APP_API_URL=https://api.jobtracker.pl > .env

            git fetch --all
            git reset --hard origin/master
            git status
            npm install
            npm run build
            pm2 delete job-app-tracker-front
            pm2 start npm --name "job-app-tracker-front" -- run "serve"
